// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPxezYGPtmPJgMxIrktMmfhWn8n4Uy0J0',
    appId: '1:557286036654:web:ba966a796fe75171bd093f',
    messagingSenderId: '557286036654',
    projectId: 'login-register-cd075',
    authDomain: 'login-register-cd075.firebaseapp.com',
    storageBucket: 'login-register-cd075.appspot.com',
    measurementId: 'G-PHCQR79E1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbeGEo2unKr_l-NltFm6GIq2A7vnhwnUQ',
    appId: '1:557286036654:android:817d6dfea7b17e18bd093f',
    messagingSenderId: '557286036654',
    projectId: 'login-register-cd075',
    storageBucket: 'login-register-cd075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaRyjpyNlSTxvNnEIg61khE6bfub1tfPU',
    appId: '1:557286036654:ios:02cad32dbc9a0a81bd093f',
    messagingSenderId: '557286036654',
    projectId: 'login-register-cd075',
    storageBucket: 'login-register-cd075.appspot.com',
    iosClientId: '557286036654-t5am0mkqi2k2catea80ks3237n3o4g3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterScreenWithBlocFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaRyjpyNlSTxvNnEIg61khE6bfub1tfPU',
    appId: '1:557286036654:ios:02cad32dbc9a0a81bd093f',
    messagingSenderId: '557286036654',
    projectId: 'login-register-cd075',
    storageBucket: 'login-register-cd075.appspot.com',
    iosClientId: '557286036654-t5am0mkqi2k2catea80ks3237n3o4g3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterScreenWithBlocFirebase',
  );
}
